import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar, Footer } from "@/components";
import { WhatsappIcon } from "@/modules";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  style: "normal",
});

export const metadata = {
  title: "iPure Reparacion de iPhone",
  description: "Generated by create next app",
  keywords: ["iPhone", "Apple", "Reparacion"],
  author: "iPure Company",
  url: "https://iPure.com",
  image: "https://iPure.com/img/logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={poppins.className}>
        <Navbar />
        <WhatsappIcon />
        {children}
        <Footer />
      </body>
    </html>
  );
}
